apiVersion: delivery.eac.dev/v1alpha1
kind: ServiceStarterPipelineBindings
metadata:
  catalogVersion: __CATALOG_RELEASE_VERSION__
  plannedCatalogVersion: 0.5.0
  releaseStatus: unreleased
spec:
  pipelineEngine: tekton
  containerBuild: dotnet-sdk
  generatedFiles:
    - target: .tekton/continuous-integration.yaml
      template: templates/pipelines-as-code/services/dotnet/continuous-integration.yaml.template
      pipeline: eac-dotnet-service-ci
    - target: .tekton/deployment.yaml
      template: templates/pipelines-as-code/deployments/promotion.yaml.template
      pipeline: eac-deployment-promotion
  forbiddenGeneratedKinds:
    - Task
    - Pipeline
  requiredServiceAccounts:
    continuousIntegration: eac-ci
    deployment: eac-deployment
