apiVersion: delivery.eac.dev/v1alpha1
kind: PipelineCatalog
metadata:
  name: eac-pipeline-catalog
spec:
  version: 0.5.0
  profiles:
    - name: nuget-ci
      family: packages
      format: nuget
      resource: eac-nuget-ci
      path: catalog/profiles/packages/nuget/pipelines/continuous-integration.yaml
      status: implemented

    - name: nuget-release-candidate
      family: packages
      format: nuget
      resource: eac-nuget-release-candidate
      path: catalog/profiles/packages/nuget/pipelines/release-candidate.yaml
      status: implemented
    - name: nuget-publish
      family: packages
      format: nuget
      resource: eac-nuget-prerelease-publication
      path: catalog/profiles/packages/nuget/pipelines/prerelease-publication.yaml
      status: implemented
    - name: nuget-stable-publish
      family: packages
      format: nuget
      resource: eac-nuget-stable-publication
      path: catalog/profiles/packages/nuget/pipelines/stable-publication.yaml
      status: implemented
    - name: npm-package
      family: packages
      format: npm
      resource: eac-npm-ci
      path: catalog/profiles/packages/npm/pipelines/continuous-integration.yaml
      publicationResource: eac-npm-publication
      publicationPath: catalog/profiles/packages/npm/pipelines/publication.yaml
      status: implemented
    - name: angular-web
      family: applications
      technology: angular
      resource: eac-angular-ci
      path: catalog/profiles/applications/angular/pipelines/continuous-integration.yaml
      status: implemented
    - name: dotnet-service
      family: services
      technology: dotnet
      resource: eac-dotnet-service-ci
      path: catalog/profiles/services/dotnet/pipelines/continuous-integration.yaml
      publicationResource: eac-dotnet-service-publication
      publicationPath: catalog/profiles/services/dotnet/pipelines/publication.yaml
      status: implemented
    - name: deployment
      family: deployments
      resource: eac-deployment-promotion
      path: catalog/profiles/deployments/pipelines/promotion.yaml
      status: implemented
  bindings:
    - name: service-starter
      path: templates/service-starter/bindings.yaml
      status: implemented
